name: PHP-CS-Fixer
on:
  pull_request:
  push:
    branches:
      - 'refs/pull/*'
      - 'main'


jobs:
  run:
    name: PHP-CS-Fixer ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.0' ]

    steps:
      -   name: Checkout
          uses: actions/checkout@v3

      -   name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: none
            php-version: ${{ matrix.php }}
            ini-values: memory_limit=-1
            tools: composer:v2

      -   name: Determine composer cache directory
          id: composer-cache
          run: echo "::set-output name=directory::$(composer config cache-dir)"

      -   name: Cache composer dependencies
          uses: actions/cache@v3.0.11
          with:
            path: ${{ steps.composer-cache.outputs.directory }}
            key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ matrix.php }}-composer-

      -   name: Install Dependencies
          run: composer update --no-progress --ansi

      -   name: PHP-CS-Fixer
          run: ./vendor/bin/php-cs-fixer fix --dry-run --diff